export { default as Setup2FA } from './Setup2FA/Setup2FA'
export { default as LoginForm } from './LoginForm/LoginForm'
export { default as BrandImage } from './BrandImage/BrandImage'
export { default as ActionButton } from './ActionButton/ActionButton'
export { default as PrivacyPolicy } from './PrivacyPolicy/PrivacyPolicy'
export { default as ParentWrapper } from './ParentWrapper/ParentWrapper'
export { default as ResetPassword } from './ResetPassword/ResetPassword'
export { default as ForgotPassword } from './ForgotPassword/ForgotPassword'
